"""agent_run + agent_run_event

Revision ID: 06642f700c48
Revises: 0f2f1f6db0a4
Create Date: 2026-06-30 23:39:04.238109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06642f700c48'
down_revision: Union[str, Sequence[str], None] = '0f2f1f6db0a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('context_ref', sa.Uuid(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_run_context_ref'), 'agent_run', ['context_ref'], unique=False)
    op.create_table('agent_run_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('event', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_run_event_run_id'), 'agent_run_event', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_run_event_run_id'), table_name='agent_run_event')
    op.drop_table('agent_run_event')
    op.drop_index(op.f('ix_agent_run_context_ref'), table_name='agent_run')
    op.drop_table('agent_run')
    # ### end Alembic commands ###
