"""add basis to ldm015

Revision ID: 0f2f1f6db0a4
Revises: e58ac7450919
Create Date: 2026-06-30 23:11:48.145908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f2f1f6db0a4'
down_revision: Union[str, Sequence[str], None] = 'e58ac7450919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ldm015_model_result', sa.Column('basis', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ldm015_model_result', 'basis')
    # ### end Alembic commands ###
