"""baseline

Revision ID: e58ac7450919
Revises: 
Create Date: 2026-06-30 21:05:59.347124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# created_at 默认值用 sa.func.now()（随方言编译：SQLite→CURRENT_TIMESTAMP、Postgres→now()），
# 而非字面量 sa.text('now()')（SQLite 无 now() 函数，插入会报 unknown function: now()）。


# revision identifiers, used by Alembic.
revision: str = 'e58ac7450919'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ldm001_project',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('background', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ldm002_material',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=False),
    sa.Column('content_form', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ldm002_material_project_id'), 'ldm002_material', ['project_id'], unique=False)
    op.create_table('ldm003_intake_record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('context_ref', sa.Uuid(), nullable=False),
    sa.Column('intake_conclusion', sa.String(length=32), nullable=False),
    sa.Column('material_ref', sa.Uuid(), nullable=True),
    sa.Column('model_result_ref', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ldm003_intake_record_context_ref'), 'ldm003_intake_record', ['context_ref'], unique=True)
    op.create_index(op.f('ix_ldm003_intake_record_project_id'), 'ldm003_intake_record', ['project_id'], unique=False)
    op.create_table('ldm015_model_result',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('applies_to_ref', sa.Uuid(), nullable=True),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('judgement', sa.String(length=32), nullable=False),
    sa.Column('process_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('process_intake_request',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=False),
    sa.Column('operator_ref', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('stop_next_action', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_intake_request_idempotency_key'), 'process_intake_request', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_process_intake_request_project_id'), 'process_intake_request', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_process_intake_request_project_id'), table_name='process_intake_request')
    op.drop_index(op.f('ix_process_intake_request_idempotency_key'), table_name='process_intake_request')
    op.drop_table('process_intake_request')
    op.drop_table('ldm015_model_result')
    op.drop_index(op.f('ix_ldm003_intake_record_project_id'), table_name='ldm003_intake_record')
    op.drop_index(op.f('ix_ldm003_intake_record_context_ref'), table_name='ldm003_intake_record')
    op.drop_table('ldm003_intake_record')
    op.drop_index(op.f('ix_ldm002_material_project_id'), table_name='ldm002_material')
    op.drop_table('ldm002_material')
    op.drop_table('ldm001_project')
    # ### end Alembic commands ###
