"""架构单元的公开接口（Protocol）—— 详设"接口"在代码里的落地。

规则（对应 docs/40 "接口按领域聚类、引用不复制"）：
**每个接口只定义一次、放在其拥有单元处、消费者 import，绝不按消费者重复定义。**
- 命名用领域角色名，不加 `Port`/`Interface` 后缀（六边形里 "port" 是概念，interface/Protocol 是机制）。
- 适配器（`InMemory*` / `Sql*` / 真实实现）结构化实现之，无需继承。

当每个单元有了自己的代码包（后续 slice），其接口从这里迁入该包。
"""
from app.interfaces.repositories import (
    ChartFindingRow,
    ChartProcessRepository,
    ChartRepository,
    ChartRevisionRow,
    ChartRow,
    ChartSuggestionRequestRow,
    ChartVerificationRequestRow,
    ChartVerificationRoundRow,
    DiagnosisBatchRow,
    DiagnosisRoundRow,
    FindingVetoRow,
    DraftRow,
    ElementCreateRow,
    ElementHistoryRow,
    FacetProjectionRow,
    ElementRow,
    FormationRequestRow,
    InflightFormationRow,
    IssueRepository,
    IssueRow,
    ItemFormationProcessRepository,
    ItemOutcomeRow,
    ItemReviewRepository,
    ItemRevisionRow,
    ItemRow,
    ItemSuggestionRow,
    ModelResultRepository,
    ReviewFindingRow,
    OperationRow,
    ProcessRecordRepository,
    ProjectRepository,
    ProjectRow,
    RecognitionRead,
    RecognizedElementRow,
    RequestContent,
    RequirementItemRepository,
    SourceAssetRepository,
    StagePayloadRow,
    SupplementRow,
    TraceLinkRepository,
    TraceLinkRow,
)
from app.interfaces.services import (
    AgentRunEventBus,
    AgentRuns,
    AuditTrail,
    ModelOrchestration,
    ProjectScope,
    TraceGraph,
)

__all__ = [
    "AgentRunEventBus",
    "AgentRuns",
    "AuditTrail",
    "ChartFindingRow",
    "ChartProcessRepository",
    "ChartRepository",
    "ChartRevisionRow",
    "ChartRow",
    "ChartSuggestionRequestRow",
    "ChartVerificationRequestRow",
    "ChartVerificationRoundRow",
    "IssueRepository",
    "IssueRow",
    "TraceLinkRepository",
    "TraceLinkRow",
    "DiagnosisBatchRow",
    "DiagnosisRoundRow",
    "FindingVetoRow",
    "DraftRow",
    "ElementCreateRow",
    "ElementHistoryRow",
    "FacetProjectionRow",
    "ElementRow",
    "FormationRequestRow",
    "InflightFormationRow",
    "ItemFormationProcessRepository",
    "ItemOutcomeRow",
    "ItemReviewRepository",
    "ItemRevisionRow",
    "ItemRow",
    "ItemSuggestionRow",
    "RequirementItemRepository",
    "SupplementRow",
    "ModelOrchestration",
    "ModelResultRepository",
    "OperationRow",
    "ProcessRecordRepository",
    "ProjectRepository",
    "ProjectRow",
    "RecognitionRead",
    "RecognizedElementRow",
    "RequestContent",
    "ReviewFindingRow",
    "ProjectScope",
    "SourceAssetRepository",
    "StagePayloadRow",
    "TraceGraph",
]
